### ISSUE TITLE
Error on DataAdpater Creation

### ISSUE THREAD

**Issue by darkwarriors** [WedjaaOpen/ElasticJasperSite#1]
Hi all,

first at all, thanks for this great project and thanks for sharing it, hope we can contribute in some way.

i have a problem when i try to create a DataAdapter, this is the details of the error when i have pushed test, for testing my configuration (host:192.168.x.x clustername: elasticsearch query facets port: 9300):

java.lang.AbstractMethodError: net.wedjaa.jasper.elasticsearch.adapter.ESAdapterFactory.createDataAdapterService(Lnet/sf/jasperreports/engine/JasperReportsContext;Lnet/sf/jasperreports/data/DataAdapter;)Lnet/sf/jasperreports/data/DataAdapterService;
    at com.jaspersoft.studio.data.DataAdapterServiceFactoryImpl.getDataAdapterService(DataAdapterServiceFactoryImpl.java:46)
    at net.sf.jasperreports.data.DataAdapterServiceUtil.getService(DataAdapterServiceUtil.java:81)
    at com.jaspersoft.studio.data.wizard.AbstractDataAdapterWizard$3.run(AbstractDataAdapterWizard.java:164)
    at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)

as we see thought wireshark and tcpdump there arent attempt to connect to 9300 tcp port. How can we solve theese issues ?

**Comment by Wedjaa** [comment]
Hi, the adapter works with JasperSoft Studio up to version 5.6.1. If you're using version 6.0 or above you will see this error. If you are using 5.6.1 let me know, in that case it would be a bug that will need looking in.

  I'll keep this open, since it's in the plans to support 6.0 at some point, with the release of the 0.6.0 version of the plugin. I have already updated the ElasticParser, need to work on the plugin for the Studio and on the Server driver.

**Comment by darkwarriors** [comment]
hi wedjaa,

thanks for the answer, after i have posted my issues i have realized that iam using a wrong version of jasper studio, with the version 5.6 it is working good.
So this mean that we need to install also jasper server 5.6 for scheduling and sharing a report, am i right? because with the last version it shouldent work.

**Comment by Wedjaa** [comment]
Correct, a version of the plugin is in the works for the 6.0 series of Jasper Reports, it will take some time since we are now in the middle of a new project that uses the 5.6. I will close this issue when the 0.6.0 version of the plugin - compatible with Jasper Reports 6.0 - will be released.
