### ISSUE TITLE
Unable to place input parameters within query

### ISSUE THREAD

**Issue by bertiepinnock** [WedjaaOpen/ElasticJasperSite#4]
Hi,

First off a small disclaimer, I'm not hugely experienced with either Elasticsearch or JasperReports, so apologies if I'm missing something simple.

It doesn't seem to be possible to place parameters (e.g.`$P{parameter_name}` ) for input controls within the Elasticsearch query, without receiving a Parse Failure exception. I'm fairly certain it's because of the {} special characters confusing things. I've tried escaping the curly brackets with no success.

Is this functionality supported by the plugin? Or am I just missing something?

Otherwise, really great plugin guys!

**Comment by Wedjaa** [comment]
Hi bertiep,

 when using parameters in the query you would use: '$P!{param}', as an example:

`
{
  "query": {
    "term": {
      "lastname": "$P!{lastname}"
    }
  }
}
`

give it a spin and let me know how it goes.

Fabio

**Comment by bertiepinnock** [comment]
I tried it just now and worked a treat.

I think I had already tried that, but turns out I had a few other mistakes that I'd missed before in there causing problems.

Thanks very much for the help and for getting back to me so quickly!
