### ISSUE TITLE
how do I install elasticjasper on jasperserver ? 

### ISSUE THREAD

**Issue by agonen** [WedjaaOpen/ElasticJasperSite#5]

**Comment by Wedjaa** [comment]
Hi agonen,

I'm working on the new release of the server side plugin for Jasper Reports and ElasticSearch. Will update this issue when I'm done.

**Comment by Wedjaa** [comment]
Hi agonen,
check out the latest release of the Elastic Jasper Server component, it comes with an easy to use installer. Try it and let me know how it goes.
