### ISSUE TITLE
Top Hits Aggregation Usage

### ISSUE THREAD

**Issue by bertiepinnock** [WedjaaOpen/ElasticJasperSite#7]
Hi again,

When querying Elasticsearch with a Top Hits aggregation (using an aggregations data adapter), the plugin reads in the hits as a single field with a class type of `org.elasticsearch.search.internal.InternalSearchHits`. This prints out in the report as something like `org.elasticsearch.search.internal.InternalSearchHits@524df193` rather than the actual contents of the hit.

Is there a way I'm missing to get the contents of the hit into the report?

Thanks very much!

**Comment by Wedjaa** [comment]
Hi bertiep,

will look into it.

**Comment by Wedjaa** [comment]
Hi bertiep,

I'm closing this issue. I have seen what the confusion may have been for you - it's a common mistake - and I decided to write a blog entry that explains what is happening and how to properly insert aggregation results into a report.

You can find the article here: [http://blog.wedjaa.net/unrolling-es-results/](http://blog.wedjaa.net/unrolling-es-results/).

Cheers,

Fabio

**Comment by bertiepinnock** [comment]
Thank you so much, that's fixed it!

Just a small thing, I think there's a typo in the blog post, I think the code snippet:
`new net.sf.jasperreports.engine.JRBeanArrayDataSource($F{top_tag_hits Hits}.getHits())`
Should be:
`new net.sf.jasperreports.engine.data.JRBeanArrayDataSource($F{top_tag_hits Hits}.getHits())`

Otherwise absolutely perfect, thank you very much again for the help!

**Comment by Wedjaa** [comment]
Thanks for spotting the typo! Fixed it... it was a botched cut and paste.
